package com.alaishat.ahmed.mobostore.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF5956E9)
val Secondary = Color(0xFF58C0EA)
val OnSurfaceVariant = Color(0xFF868686)
val Background = Color(0xFFE5E5E5)
val Outline = Color(0xFF868686)
val OutlineVariant = Color(0xFFE3E3E3)

val md_theme_light_primary = Color(0xFF4C48DC)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE2DFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF0C006A)
val md_theme_light_secondary = Color(0xFF006684)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF97F0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FEFF)
val md_theme_light_onBackground = Color(0xFF001F24)
val md_theme_light_surface = Color(0xFFF6FEFF)
val md_theme_light_onSurface = Color(0xFF001F24)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_inverseOnSurface = Color(0xFFD0F8FF)
val md_theme_light_inverseSurface = Color(0xFF00363D)
val md_theme_light_inversePrimary = Color(0xFFC2C1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4C48DC)

val md_theme_dark_primary = Color(0xFFC2C1FF)
val md_theme_dark_onPrimary = Color(0xFF1900A7)
val md_theme_dark_primaryContainer = Color(0xFF3229C4)
val md_theme_dark_onPrimaryContainer = Color(0xFFE2DFFF)
val md_theme_dark_secondary = Color(0xFF68D3FF)
val md_theme_dark_onSecondary = Color(0xFF003546)
val md_theme_dark_secondaryContainer = Color(0xFF004D64)
val md_theme_dark_onSecondaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_tertiary = Color(0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F24)
val md_theme_dark_onBackground = Color(0xFF97F0FF)
val md_theme_dark_surface = Color(0xFF001F24)
val md_theme_dark_onSurface = Color(0xFF97F0FF)
val md_theme_dark_surfaceVariant = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF001F24)
val md_theme_dark_inverseSurface = Color(0xFF97F0FF)
val md_theme_dark_inversePrimary = Color(0xFF4C48DC)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC2C1FF)


val seed = Color(0xFF5956E9)
